/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.BillPayDAO;
import java.lang.reflect.Array;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.BillPay;
import util.Alert;

public class BillPayView extends javax.swing.JDialog {

    /**
     * Creates new form PaymentView
     */
    public BillPayView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        buildTable("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        btCancel = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        btSave = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        edIdbuy = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        edId = new javax.swing.JTextField();
        edIdEmployee = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txDescription = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        cbSettled = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        edType = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        edValue = new javax.swing.JFormattedTextField();
        edTotalValue = new javax.swing.JFormattedTextField();
        edDate = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btEdit = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btSearch = new javax.swing.JButton();
        edSearch = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(90, 90, 90));
        setPreferredSize(new java.awt.Dimension(832, 494));

        jPanel1.setBackground(new java.awt.Color(60, 60, 60));
        jPanel1.setForeground(new java.awt.Color(30, 30, 30));
        jPanel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        jTabbedPane1.setBackground(new java.awt.Color(60, 60, 60));
        jTabbedPane1.setForeground(new java.awt.Color(30, 30, 30));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jTabbedPane1.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(90, 90, 90));

        btCancel.setBackground(new java.awt.Color(200, 76, 88));
        btCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btCancel.setForeground(new java.awt.Color(255, 255, 255));
        btCancel.setText("Cancelar");
        btCancel.setBorderPainted(false);
        btCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCancel.setFocusPainted(false);
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("DATA DE EMISSÃO");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("ID DA COMPRA");

        btSave.setBackground(new java.awt.Color(99, 154, 103));
        btSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btSave.setForeground(new java.awt.Color(255, 255, 255));
        btSave.setText("Salvar");
        btSave.setBorderPainted(false);
        btSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSave.setFocusPainted(false);
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSavebtSaveActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("VALOR PAGO");

        edIdbuy.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID");

        edId.setEditable(false);
        edId.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        edIdEmployee.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("ID DO FUNCIONÁRIO");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DESCRIÇÃO");

        txDescription.setColumns(20);
        txDescription.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txDescription.setRows(5);
        jScrollPane2.setViewportView(txDescription);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("VALOR TOTAL");

        cbSettled.setBackground(new java.awt.Color(90, 90, 90));
        cbSettled.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbSettled.setForeground(new java.awt.Color(255, 255, 255));
        cbSettled.setText("QUITADA");
        cbSettled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSettledActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TIPO");

        edType.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        edType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edTypeActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CONTAS A PAGAR");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        edValue.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        edValue.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edValueActionPerformed(evt);
            }
        });

        edTotalValue.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        edTotalValue.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edTotalValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edTotalValueActionPerformed(evt);
            }
        });

        try {
            edDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edDate.setToolTipText("formato dd/mm/aaaa");
        edDate.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edId, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel29)
                                            .addComponent(edDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(edType, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbSettled))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel30)
                                            .addComponent(edIdbuy, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel34)
                                            .addComponent(edIdEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(edValue, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(edTotalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 314, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(313, 313, 313))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(btCancel)
                                .addGap(18, 18, 18)
                                .addComponent(btSave)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edValue, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edTotalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(jLabel34))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edIdbuy, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edIdEmployee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edDate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edType, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSettled)))))
        );

        jTabbedPane1.addTab("CONTAS A PAGAR", jPanel2);

        jPanel3.setBackground(new java.awt.Color(90, 90, 90));
        jPanel3.setForeground(new java.awt.Color(90, 90, 90));

        table.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ID DA COMPRA", "ID DO FUNCIONÁRIO", "DESCRIÇÃO", "VALOR PAGO", "VALOR TOTAL", "DATA DE EMISSÃO", "QUITADA", "TIPO DE CONTA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setToolTipText("");
        jScrollPane1.setViewportView(table);

        btEdit.setBackground(new java.awt.Color(99, 154, 103));
        btEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_edit_white_18dp.png"))); // NOI18N
        btEdit.setBorderPainted(false);
        btEdit.setFocusPainted(false);
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });

        btDelete.setBackground(new java.awt.Color(200, 76, 88));
        btDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_delete_white_18dp.png"))); // NOI18N
        btDelete.setBorderPainted(false);
        btDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btDelete.setFocusPainted(false);
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        btSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_search_white_18dp.png"))); // NOI18N
        btSearch.setToolTipText("");
        btSearch.setBorderPainted(false);
        btSearch.setContentAreaFilled(false);
        btSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSearch.setFocusPainted(false);
        btSearch.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btSearch.setIconTextGap(7);
        btSearch.setMargin(new java.awt.Insets(1, 14, 1, 14));
        btSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });

        edSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        edSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edSearchActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("LISTA DE CONTAS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(btEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(jLabel6)
                .addGap(0, 316, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("LISTAR CONTAS", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Recebimento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        int selectedRow = table.getSelectedRow();
        if (selectedRow >= 0) {
            BillPay bpay = new BillPay();
            bpay.setId_bill_pay(Integer.parseInt(table.getValueAt(selectedRow, 0).toString()));
            BillPayDAO.delete(bpay);
            buildTable("");
            jTabbedPane1.setSelectedIndex(1);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um item da tabela!");
        }
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        int selectedRow = table.getSelectedRow();
        if (selectedRow >= 0) {
            BillPay bpay = new BillPay();
            bpay.setId_bill_pay(Integer.parseInt(table.getValueAt(selectedRow, 0).toString()));
            edIdbuy.setText(table.getValueAt(selectedRow, 1).toString());
            edIdEmployee.setText(table.getValueAt(selectedRow, 2).toString());
            txDescription.setText(table.getValueAt(selectedRow, 3).toString());
            edValue.setText(table.getValueAt(selectedRow, 4).toString());
            edTotalValue.setText(table.getValueAt(selectedRow, 5).toString());
            edDate.setText(table.getValueAt(selectedRow, 6).toString());
            edId.setText(table.getValueAt(selectedRow, 0).toString());
            btSave.setVisible(true);
            edId.setVisible(true);
            jLabel1.setVisible(true);
            edId.setEditable(false);
            jTabbedPane1.setSelectedIndex(0);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um item da tabela!");
        }
    }//GEN-LAST:event_btEditActionPerformed

    private void btSavebtSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSavebtSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSavebtSaveActionPerformed

    private void edSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edSearchActionPerformed

    private void btSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchActionPerformed
        // TODO add your handling code here:
        buildTable(btSearch.getText());
    }//GEN-LAST:event_btSearchActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btCancelActionPerformed

    private void cbSettledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSettledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSettledActionPerformed

    private void edTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edTypeActionPerformed

    private void edValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edValueActionPerformed

    private void edTotalValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edTotalValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edTotalValueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */    }

    private boolean verifyValuesIfItsNotEmpty() {
        boolean haveEmptyValue = false;

        if (edId.getText().isEmpty()) {
            haveEmptyValue = true;
        }
        if (edIdbuy.getText().isEmpty()) {
            haveEmptyValue = true;
        }
        if (edIdEmployee.getText().isEmpty()) {
            haveEmptyValue = true;
        }
        if (edDate.getText().isEmpty()) {
            haveEmptyValue = true;
        }
        if (edTotalValue.getText().isEmpty()) {
            haveEmptyValue = true;
        }
        if (edType.getText().isEmpty()) {
            haveEmptyValue = true;
        }
        if (edValue.getText().isEmpty()) {
            haveEmptyValue = true;
        }
        if (txDescription.getText().isEmpty()) {
            haveEmptyValue = true;
        }        
        return haveEmptyValue;
    }

    private void saveProduct() {
        if (!verifyValuesIfItsNotEmpty()) {
            BillPay bpay = new BillPay();
            bpay.setId_bill_pay(Integer.parseInt(edId.getText()));
            bpay.setId_buy_bill_pay(Integer.parseInt(edIdbuy.getText()));
            bpay.setId_employee_buy_bill_pay(Integer.parseInt(edIdEmployee.getText()));
            bpay.setDescription_bill(txDescription.getText());
            bpay.setValue_paidOut_bill_pay(Float.parseFloat(edValue.getText()));
            bpay.setTotal_amount_bill_pay(Float.parseFloat(edTotalValue.getText()));
            bpay.setDate_bill(edDate.getText());
            if (cbSettled.isSelected()){
                bpay.setSettled_bill_pay(true);
            }else{
                bpay.setSettled_bill_pay(false);
            }
            bpay.setType_bill_pay(edType.getText());
            BillPayDAO.insert(bpay);
            buildTable("");
            jTabbedPane1.setSelectedIndex(1);
            clear();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Algum campo está em branco", null, JOptionPane.WARNING_MESSAGE);
        }

    }

    private void buildTable(String name) {
        BillPayDAO bpDAO = new BillPayDAO();
        List<BillPay> bplist = bpDAO.getListBillPay(name);
        DefaultTableModel tableModel = (DefaultTableModel) table.getModel();
        tableModel.setRowCount(0);

        for (BillPay bpay : bplist) {
            tableModel.addRow(new Object[]{bpay.getId_bill_pay(), bpay.getId_buy_bill_pay(), bpay.getId_employee_buy_bill_pay(), bpay.getDescription_bill(), bpay.getValue_paidOut_bill_pay(), bpay.getTotal_amount_bill_pay(), bpay.getDate_bill(), bpay.isSettled_bill_pay(), bpay.getType_bill_pay()});
        }

    }

    private void clear() {
        edId.setText(null);
        edIdbuy.setText(null);
        edIdEmployee.setText(null);
        txDescription.setText(null);
        edValue.setText(null);
        edTotalValue.setText(null);
        edDate.setText(null);
        cbSettled.setSelected(false);
        edType.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btSave;
    private javax.swing.JButton btSearch;
    private javax.swing.JCheckBox cbSettled;
    private javax.swing.JFormattedTextField edDate;
    private javax.swing.JTextField edId;
    private javax.swing.JTextField edIdEmployee;
    private javax.swing.JTextField edIdbuy;
    private javax.swing.JTextField edSearch;
    private javax.swing.JFormattedTextField edTotalValue;
    private javax.swing.JTextField edType;
    private javax.swing.JFormattedTextField edValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextArea txDescription;
    // End of variables declaration//GEN-END:variables
}
