/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ClientDAO;
import dao.EmployeeDAO;
import dao.SchedulingDAO;
import dao.ServiceDAO;
import dao.UserDAO;
import java.sql.Time;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import model.Client;
import model.Employee;
import model.Person;
import model.Scheduling;
import model.Service;
import util.Alert;

/**
 *
 * @author lacft
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form HomeDefault
     */
    public Home() {
        initComponents();
        setCurrentDate();
        buildTable(dateSearch.getText());
        chargeCbService();
        chargeCbClient();
        chargeCbFunctionary();

        btDelete.setVisible(false);
        btnAtt.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDelete = new javax.swing.JButton();
        sideBarPanel = new javax.swing.JPanel();
        btnUsers = new javax.swing.JButton();
        btnCashRegister = new javax.swing.JButton();
        btnProductSuppliers = new javax.swing.JButton();
        btnRoles = new javax.swing.JButton();
        btnEmployee = new javax.swing.JButton();
        btnProducts = new javax.swing.JButton();
        btnServices = new javax.swing.JButton();
        btnSales = new javax.swing.JButton();
        btnBuys = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnReports = new javax.swing.JButton();
        btnBrands = new javax.swing.JButton();
        btnPayment = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbService = new javax.swing.JComboBox<>();
        editDate = new javax.swing.JFormattedTextField();
        cbClient = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnAtt = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        cbFunctionary = new javax.swing.JComboBox<>();
        editStartHour = new javax.swing.JFormattedTextField();
        btSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dateSearch = new javax.swing.JFormattedTextField();
        editEndHour = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();

        btnDelete.setText("Apagar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setResizable(false);

        sideBarPanel.setBackground(new java.awt.Color(60, 60, 60));

        btnUsers.setBackground(new java.awt.Color(30, 30, 30));
        btnUsers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUsers.setForeground(new java.awt.Color(255, 255, 255));
        btnUsers.setText("Usuários");
        btnUsers.setBorderPainted(false);
        btnUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnUsers.setFocusPainted(false);
        btnUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersActionPerformed(evt);
            }
        });

        btnCashRegister.setBackground(new java.awt.Color(30, 30, 30));
        btnCashRegister.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCashRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnCashRegister.setText("Caixa");
        btnCashRegister.setBorderPainted(false);
        btnCashRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCashRegister.setFocusPainted(false);
        btnCashRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashRegisterActionPerformed(evt);
            }
        });

        btnProductSuppliers.setBackground(new java.awt.Color(30, 30, 30));
        btnProductSuppliers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnProductSuppliers.setForeground(new java.awt.Color(255, 255, 255));
        btnProductSuppliers.setText("Fornecedores");
        btnProductSuppliers.setBorderPainted(false);
        btnProductSuppliers.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnProductSuppliers.setFocusPainted(false);
        btnProductSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductSuppliersActionPerformed(evt);
            }
        });

        btnRoles.setBackground(new java.awt.Color(30, 30, 30));
        btnRoles.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRoles.setForeground(new java.awt.Color(255, 255, 255));
        btnRoles.setText("Cargos");
        btnRoles.setBorderPainted(false);
        btnRoles.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRoles.setFocusPainted(false);
        btnRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRolesActionPerformed(evt);
            }
        });

        btnEmployee.setBackground(new java.awt.Color(30, 30, 30));
        btnEmployee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btnEmployee.setText("Pessoas");
        btnEmployee.setBorderPainted(false);
        btnEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEmployee.setFocusPainted(false);
        btnEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeActionPerformed(evt);
            }
        });

        btnProducts.setBackground(new java.awt.Color(30, 30, 30));
        btnProducts.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnProducts.setForeground(new java.awt.Color(255, 255, 255));
        btnProducts.setText("Produtos");
        btnProducts.setBorderPainted(false);
        btnProducts.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnProducts.setFocusPainted(false);
        btnProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductsActionPerformed(evt);
            }
        });

        btnServices.setBackground(new java.awt.Color(30, 30, 30));
        btnServices.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnServices.setForeground(new java.awt.Color(255, 255, 255));
        btnServices.setText("Serviços");
        btnServices.setBorderPainted(false);
        btnServices.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnServices.setFocusPainted(false);
        btnServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicesActionPerformed(evt);
            }
        });

        btnSales.setBackground(new java.awt.Color(30, 30, 30));
        btnSales.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSales.setForeground(new java.awt.Color(255, 255, 255));
        btnSales.setText("Vendas");
        btnSales.setBorderPainted(false);
        btnSales.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSales.setFocusPainted(false);
        btnSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalesActionPerformed(evt);
            }
        });

        btnBuys.setBackground(new java.awt.Color(30, 30, 30));
        btnBuys.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuys.setForeground(new java.awt.Color(255, 255, 255));
        btnBuys.setText("Compras");
        btnBuys.setBorderPainted(false);
        btnBuys.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBuys.setFocusPainted(false);
        btnBuys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuysActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(90, 90, 90));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo200pxxx.png"))); // NOI18N

        btnReports.setBackground(new java.awt.Color(30, 30, 30));
        btnReports.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReports.setForeground(new java.awt.Color(255, 255, 255));
        btnReports.setText("Relatórios");
        btnReports.setBorderPainted(false);
        btnReports.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnReports.setFocusPainted(false);
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });

        btnBrands.setBackground(new java.awt.Color(30, 30, 30));
        btnBrands.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBrands.setForeground(new java.awt.Color(255, 255, 255));
        btnBrands.setText("Marcas");
        btnBrands.setBorderPainted(false);
        btnBrands.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBrands.setFocusPainted(false);
        btnBrands.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrandsActionPerformed(evt);
            }
        });

        btnPayment.setBackground(new java.awt.Color(30, 30, 30));
        btnPayment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPayment.setForeground(new java.awt.Color(255, 255, 255));
        btnPayment.setText("Contas");
        btnPayment.setBorderPainted(false);
        btnPayment.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPayment.setFocusPainted(false);
        btnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sideBarPanelLayout = new javax.swing.GroupLayout(sideBarPanel);
        sideBarPanel.setLayout(sideBarPanelLayout);
        sideBarPanelLayout.setHorizontalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanelLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(sideBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRoles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProductSuppliers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                    .addComponent(btnProducts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnServices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuys, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCashRegister, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReports, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBrands, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sideBarPanelLayout.setVerticalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btnCashRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProductSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnServices, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSales, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuys, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRoles, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReports, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBrands, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPayment)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(90, 90, 90));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agendamentos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1106, -1));

        cbService.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbService.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbService.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbServiceItemStateChanged(evt);
            }
        });
        cbService.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbServiceAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cbService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbServiceActionPerformed(evt);
            }
        });
        jPanel1.add(cbService, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 337, 324, -1));

        try {
            editDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        editDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(editDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 195, 91, 32));

        cbClient.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbClient.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbClientAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cbClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbClientActionPerformed(evt);
            }
        });
        jPanel1.add(cbClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 115, 324, -1));

        btnSave.setBackground(new java.awt.Color(99, 154, 103));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Salvar");
        btnSave.setBorderPainted(false);
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSave.setFocusPainted(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 450, 100, -1));

        btnAtt.setBackground(new java.awt.Color(87, 126, 244));
        btnAtt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAtt.setForeground(new java.awt.Color(255, 255, 255));
        btnAtt.setText("Atualizar");
        btnAtt.setBorderPainted(false);
        btnAtt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAtt.setFocusPainted(false);
        btnAtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 450, 100, -1));

        btnCancel.setBackground(new java.awt.Color(200, 76, 88));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancelar");
        btnCancel.setBorderPainted(false);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancel.setFocusPainted(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 450, 100, -1));

        btDelete.setBackground(new java.awt.Color(200, 76, 88));
        btDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btDelete.setForeground(new java.awt.Color(255, 255, 255));
        btDelete.setText("Apagar");
        btDelete.setBorderPainted(false);
        btDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btDelete.setFocusPainted(false);
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 450, 100, -1));

        cbFunctionary.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbFunctionary.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbFunctionaryAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(cbFunctionary, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 267, 324, -1));

        try {
            editStartHour.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        editStartHour.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editStartHour.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                editStartHourFocusLost(evt);
            }
        });
        jPanel1.add(editStartHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(893, 195, 58, 32));

        btSearch.setBackground(new java.awt.Color(90, 90, 90));
        btSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_search_white_18dp.png"))); // NOI18N
        btSearch.setBorderPainted(false);
        btSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btSearch.setFocusPainted(false);
        btSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 88, 50, 30));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Horário", "Cliente", "Serviço", "Funcionário"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 153, 758, 599));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Serviço");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 315, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Data");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 173, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Horário");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(893, 173, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Funcionário");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 245, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Cliente");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 90, 50, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DIA:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 30, 20));

        try {
            dateSearch.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dateSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(dateSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 87, 87, 32));

        try {
            editEndHour.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        editEndHour.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(editEndHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(967, 195, 58, 32));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("-");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(957, 204, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 886, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCashRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashRegisterActionPerformed
        // TODO add your handling code here:
        CashRegisterView view = new CashRegisterView(this, rootPaneCheckingEnabled);
        view.setLocationRelativeTo(view);
        view.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnCashRegisterActionPerformed

    private void btnUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersActionPerformed
        // TODO add your handling code here:
        UserView view = new UserView(this, rootPaneCheckingEnabled);
        view.setLocationRelativeTo(view);
        view.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnUsersActionPerformed

    private void btnProductSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductSuppliersActionPerformed
        // TODO add your handling code here:
        ProductSupplierRegisterView view = new ProductSupplierRegisterView(this, rootPaneCheckingEnabled);
        view.setLocationRelativeTo(view);
        view.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnProductSuppliersActionPerformed

    private void btnEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeActionPerformed
        // TODO add your handling code here:
        PersonView view = new PersonView(this, rootPaneCheckingEnabled);
        view.setLocationRelativeTo(view);
        view.setVisible(rootPaneCheckingEnabled);

        chargeCbClient();
        chargeCbFunctionary();

    }//GEN-LAST:event_btnEmployeeActionPerformed

    private void btnRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRolesActionPerformed
        // TODO add your handling code here:
        RoleRegisterView view = new RoleRegisterView(this, rootPaneCheckingEnabled);
        view.setLocationRelativeTo(view);
        view.setVisible(rootPaneCheckingEnabled);

    }//GEN-LAST:event_btnRolesActionPerformed

    private void btnProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductsActionPerformed
        // TODO add your handling code here:
        ProductView view = new ProductView(this, rootPaneCheckingEnabled);
        view.setLocationRelativeTo(view);
        view.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnProductsActionPerformed

    private void btnServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicesActionPerformed
        // TODO add your handling code here:
        ServiceRegisterView view = new ServiceRegisterView(this, rootPaneCheckingEnabled);
        view.setLocationRelativeTo(view);
        view.setVisible(rootPaneCheckingEnabled);

        chargeCbService();
    }//GEN-LAST:event_btnServicesActionPerformed

    private void cbServiceAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbServiceAncestorAdded

    }//GEN-LAST:event_cbServiceAncestorAdded

    private void cbClientAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbClientAncestorAdded

    }//GEN-LAST:event_cbClientAncestorAdded

    private void cbClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbClientActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        saveScheduling();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void cbFunctionaryAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbFunctionaryAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFunctionaryAncestorAdded

    private void btSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchActionPerformed

        buildTable(dateSearch.getText());
    }//GEN-LAST:event_btSearchActionPerformed

    private void btnSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesActionPerformed
        // TODO add your handling code here:
        SalesView view = new SalesView(this, rootPaneCheckingEnabled);
        view.setLocationRelativeTo(view);
        view.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnSalesActionPerformed

    private void btnBuysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuysActionPerformed
        // TODO add your handling code here:
        BuyView view = new BuyView(this, rootPaneCheckingEnabled);
        view.setLocationRelativeTo(view);
        view.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnBuysActionPerformed

    private void btnAttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttActionPerformed
        // TODO add your handling code here:

        if (verifyForm()) {
            Scheduling scheduling = new Scheduling();

            scheduling.setService((Service) cbService.getSelectedItem());

            scheduling.setDate(editDate.getText());
            scheduling.setStartTime(editStartHour.getText());
            scheduling.setEndTime(editEndHour.getText());

            scheduling.setFunctionary((Employee) cbFunctionary.getSelectedItem());

            scheduling.setClient((Client) cbClient.getSelectedItem());

            SchedulingDAO.update(scheduling);
            buildTable(editDate.getText());
        }

    }//GEN-LAST:event_btnAttActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int index = table.getSelectedRow();
        editStartHour.setText(((Scheduling) table.getValueAt(index, 0)).getStartTime());
        editEndHour.setText(((Scheduling) table.getValueAt(index, 0)).getEndTime());
        //editEndHour.setText(String.valueOf(table.getValueAt(index, 0)).);

        editDate.setText(dateSearch.getText());

        btnSave.setVisible(false);
        btnAtt.setVisible(true);
        btDelete.setVisible(true);

        for (int i = 0; i < cbClient.getItemCount(); i++) {
            if (((Client) cbClient.getItemAt(i)).getId() == ((Client) table.getValueAt(index, 1)).getId()) {
                cbClient.setSelectedIndex(i);
            }
        }
        
        
        for (int i = 0; i < cbService.getItemCount(); i++) {
            if (((Service) cbService.getItemAt(i)).getIdService()== ((Service) table.getValueAt(index, 2)).getIdService()) {
                cbService.setSelectedIndex(i);
            }
        }
        
        for (int i = 0; i < cbFunctionary.getItemCount(); i++) {
            if (((Employee) cbFunctionary.getItemAt(i)).getId() == ((Employee) table.getValueAt(index, 3)).getId()) {
                cbFunctionary.setSelectedIndex(i);
            }
        }
        
    }//GEN-LAST:event_tableMouseClicked

    private void cbServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbServiceActionPerformed
        // TODO add your handling code here:

        if (!editStartHour.getText().equals("  :  ")) {
            calculateEndHour();
        }
    }//GEN-LAST:event_cbServiceActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        // TODO add your handling code here:

        int index = table.getSelectedRow();
        boolean accepted = Alert.showOptionDialog("Deseja desmarcar esse horário?", "Confirmação");
        if (accepted) {
            SchedulingDAO.delete((Scheduling) table.getValueAt(index, 0));
            buildTable(editDate.getText());
            clearForm();
        }
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void cbServiceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbServiceItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_cbServiceItemStateChanged

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        // TODO add your handling code here:
        ReportView view = new ReportView(this, rootPaneCheckingEnabled);
        view.setLocationRelativeTo(view);
        view.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnBrandsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrandsActionPerformed
        // TODO add your handling code here:
        BrandView view = new BrandView(this, rootPaneCheckingEnabled);
        view.setLocationRelativeTo(view);
        view.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnBrandsActionPerformed

    private void editStartHourFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editStartHourFocusLost
        // TODO add your handling code here:
        if (cbService.getSelectedItem() != null) {
            calculateEndHour();
        }
    }//GEN-LAST:event_editStartHourFocusLost

    private void btnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentActionPerformed
        // TODO add your handling code here:
        PaymentView view = new PaymentView(this, rootPaneCheckingEnabled);
        view.setLocationRelativeTo(view);
        view.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnPaymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    private void saveScheduling() {
        if (verifyForm()) {
            Scheduling scheduling = new Scheduling();

            scheduling.setService((Service) cbService.getSelectedItem());

            scheduling.setDate(editDate.getText());
            scheduling.setStartTime(editStartHour.getText());
            scheduling.setEndTime(editEndHour.getText());

            scheduling.setFunctionary((Employee) cbFunctionary.getSelectedItem());

            scheduling.setClient((Client) cbClient.getSelectedItem());

            SchedulingDAO.insert(scheduling);
            buildTable(editDate.getText());
            clearForm();
        }

    }

    public void chargeCbService() {
        List<Service> serviceList = ServiceDAO.getListService("");
        cbService.removeAllItems();

        for (Service sc : serviceList) {
            cbService.addItem(sc);
        }

        cbService.setSelectedItem(null);
    }

    public void chargeCbFunctionary() {
        List<Employee> employees = EmployeeDAO.getListEmployee("");
        cbFunctionary.removeAllItems();

        for (Employee e : employees) {
            cbFunctionary.addItem(e);
        }

        cbFunctionary.setSelectedItem(null);
    }

    public void chargeCbClient() {
        List<Client> clients = ClientDAO.getListClient("");
        cbClient.removeAllItems();

        for (Client c : clients) {
            cbClient.addItem(c);
        }

        cbClient.setSelectedItem(null);
    }

    private void buildTable(String date) {
        dateSearch.setText(date);
        SchedulingDAO scDAO = new SchedulingDAO();
        List<Scheduling> list = scDAO.getListSchedule(date);
        DefaultTableModel tableModel = (DefaultTableModel) table.getModel();
        tableModel.setRowCount(0);

        for (Scheduling sc : list) {
            tableModel.addRow(new Object[]{sc, sc.getClient(), sc.getService(), sc.getFunctionary()});
        }
    }

    private void setCurrentDate() {
        Date date = new Date(System.currentTimeMillis());
        SimpleDateFormat dateFormatter = new SimpleDateFormat("ddMMyyyy");

        String currentDate = dateFormatter.format(date);
        System.out.print(currentDate);
        dateSearch.setText(currentDate);
        editDate.setText(currentDate);
    }

    private void calculateEndHour() {
        Service service = (Service) cbService.getSelectedItem();
        SimpleDateFormat formatter = new SimpleDateFormat("HH:mm");
        try {
            Date date = formatter.parse(editStartHour.getText());
            Time time = new Time(date.getTime());
            System.out.println(time);

            Calendar cal = Calendar.getInstance();
            cal.setTime(time);
            cal.add(Calendar.MINUTE, service.getDurationService());
            String endHour = formatter.format(cal.getTime());
            System.out.println(endHour);
            editEndHour.setText(endHour);
        } catch (ParseException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private boolean verifyForm() {
        if (cbClient.getSelectedItem() == null) {
            Alert.showMessageDialog("Selecione um cliente!");
        } else if (cbFunctionary.getSelectedItem() == null) {
            Alert.showMessageDialog("Selecione um funcionário!");
        } else if (cbService.getSelectedItem() == null) {
            Alert.showMessageDialog("Selecione um serviço!");
        } else if (editDate.getText().equals("  /  /   ")) {
            Alert.showMessageDialog("Insira uma data!");
        } else if (editStartHour.getText().equals("  :  ")) {
            Alert.showMessageDialog("Insira um horário inicial!");
        } else if (editStartHour.getText().equals("  :  ")) {
            Alert.showMessageDialog("Insira um horário final!");
        } else {
            return true;
        }
        return false;
    }

    private void clearForm() {
        btnSave.setVisible(true);
        btnAtt.setVisible(false);
        btDelete.setVisible(false);
        editStartHour.setText(null);
        editEndHour.setText(null);
        cbClient.setSelectedItem(null);
        cbFunctionary.setSelectedItem(null);
        cbService.setSelectedItem(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btSearch;
    private javax.swing.JButton btnAtt;
    private javax.swing.JButton btnBrands;
    private javax.swing.JButton btnBuys;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCashRegister;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEmployee;
    private javax.swing.JButton btnPayment;
    private javax.swing.JButton btnProductSuppliers;
    private javax.swing.JButton btnProducts;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnRoles;
    private javax.swing.JButton btnSales;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnServices;
    private javax.swing.JButton btnUsers;
    private javax.swing.JComboBox<Object> cbClient;
    private javax.swing.JComboBox<Object> cbFunctionary;
    private javax.swing.JComboBox<Object> cbService;
    private javax.swing.JFormattedTextField dateSearch;
    private javax.swing.JFormattedTextField editDate;
    private javax.swing.JFormattedTextField editEndHour;
    private javax.swing.JFormattedTextField editStartHour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel sideBarPanel;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
