/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ReceivementDAO;
import java.lang.reflect.Array;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Receivement;
import util.Alert;

/**
 *
 * @author daniel
 */
public class ReceivementView extends javax.swing.JDialog {

    /**
     * Creates new form ReceivementView
     */
    public ReceivementView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        buildTable("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        edTotalAmountReceivable = new javax.swing.JTextField();
        btCancel = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        btSave = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        edIdAccount = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        edId = new javax.swing.JTextField();
        edIdCashier = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        cbPagForm = new javax.swing.JComboBox<>();
        edDateReceivement = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btEdit = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btSearch = new javax.swing.JButton();
        edSearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Recebimentos");
        setResizable(false);

        jTabbedPane1.setBackground(new java.awt.Color(60, 60, 60));
        jTabbedPane1.setForeground(new java.awt.Color(30, 30, 30));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jTabbedPane1.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(90, 90, 90));
        jPanel2.setLayout(null);

        edTotalAmountReceivable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel2.add(edTotalAmountReceivable);
        edTotalAmountReceivable.setBounds(60, 280, 100, 32);

        btCancel.setBackground(new java.awt.Color(200, 76, 88));
        btCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btCancel.setForeground(new java.awt.Color(255, 255, 255));
        btCancel.setText("Cancelar");
        btCancel.setBorderPainted(false);
        btCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCancel.setFocusPainted(false);
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });
        jPanel2.add(btCancel);
        btCancel.setBounds(460, 190, 110, 28);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("DATA DO RECEBIMENTO");
        jPanel2.add(jLabel29);
        jLabel29.setBounds(60, 200, 162, 20);

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("ID CONTA RECEBIMENTO");
        jPanel2.add(jLabel30);
        jLabel30.setBounds(60, 140, 170, 20);

        btSave.setBackground(new java.awt.Color(99, 154, 103));
        btSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btSave.setForeground(new java.awt.Color(255, 255, 255));
        btSave.setText("Salvar");
        btSave.setBorderPainted(false);
        btSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSave.setFocusPainted(false);
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSavebtSaveActionPerformed(evt);
            }
        });
        jPanel2.add(btSave);
        btSave.setBounds(460, 150, 110, 28);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("FORMA DE PAGAMENTO");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(240, 200, 170, 20);

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("VALOR TOTAL");
        jPanel2.add(jLabel32);
        jLabel32.setBounds(60, 260, 100, 20);

        edIdAccount.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel2.add(edIdAccount);
        edIdAccount.setBounds(60, 160, 170, 26);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(60, 80, 60, 20);

        edId.setEditable(false);
        edId.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel2.add(edId);
        edId.setBounds(60, 100, 60, 26);

        edIdCashier.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel2.add(edIdCashier);
        edIdCashier.setBounds(240, 160, 160, 26);

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("ID CAIXA RECEBIMENTO");
        jPanel2.add(jLabel34);
        jLabel34.setBounds(240, 140, 170, 20);

        cbPagForm.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cbPagForm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Cartão de Crédito", "Cheque", "Boleto Bancário", "" }));
        cbPagForm.setSelectedIndex(-1);
        jPanel2.add(cbPagForm);
        cbPagForm.setBounds(240, 220, 160, 26);

        try {
            edDateReceivement.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edDateReceivement.setToolTipText("fomato dd/mm/aaaa");
        edDateReceivement.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel2.add(edDateReceivement);
        edDateReceivement.setBounds(60, 220, 60, 26);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CADASTRAR RECEBIMENTO");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(160, 30, 330, 20);

        jTabbedPane1.addTab("CADASTRAR RECEBIMENTO", jPanel2);

        jPanel3.setBackground(new java.awt.Color(90, 90, 90));
        jPanel3.setLayout(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Id Conta ", "Id Caixa", "Data Recebimento", "Forma de Pagamento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setToolTipText("");
        jScrollPane1.setViewportView(table);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 100, 617, 335);

        btEdit.setBackground(new java.awt.Color(87, 126, 244));
        btEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_edit_white_18dp.png"))); // NOI18N
        btEdit.setBorderPainted(false);
        btEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btEdit.setFocusPainted(false);
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });
        jPanel3.add(btEdit);
        btEdit.setBounds(40, 50, 48, 33);

        btDelete.setBackground(new java.awt.Color(200, 76, 88));
        btDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_delete_white_18dp.png"))); // NOI18N
        btDelete.setBorderPainted(false);
        btDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btDelete.setFocusPainted(false);
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btDelete);
        btDelete.setBounds(110, 50, 48, 33);

        btSearch.setBackground(new java.awt.Color(90, 90, 90));
        btSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_search_white_18dp.png"))); // NOI18N
        btSearch.setBorderPainted(false);
        btSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSearch.setFocusPainted(false);
        btSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });
        jPanel3.add(btSearch);
        btSearch.setBounds(560, 50, 48, 33);

        edSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edSearchActionPerformed(evt);
            }
        });
        jPanel3.add(edSearch);
        edSearch.setBounds(230, 50, 336, 33);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LISTA DE RECEBIMENTOS");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(160, 0, 289, 32);

        jTabbedPane1.addTab("LISTAR RECEBIMENTO", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Recebimento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        int selectedRow = table.getSelectedRow();
        if (selectedRow >= 0) {
            Receivement rcvmt = new Receivement();
            rcvmt.setId_receivement(Integer.parseInt(table.getValueAt(selectedRow, 0).toString()));
            ReceivementDAO.delete(rcvmt);
            buildTable("");
            jTabbedPane1.setSelectedIndex(1);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um item da tabela!");
        }
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        int selectedRow = table.getSelectedRow();
        if (selectedRow >= 0) {
            Receivement rcvmt = new Receivement();
            rcvmt.setId_receivement(Integer.parseInt(table.getValueAt(selectedRow, 0).toString()));
            edIdAccount.setText(table.getValueAt(selectedRow, 1).toString());
            edIdCashier.setText(table.getValueAt(selectedRow, 2).toString());
            edDateReceivement.setText(table.getValueAt(selectedRow, 3).toString());
            edTotalAmountReceivable.setText(table.getValueAt(selectedRow, 4).toString());
            edId.setText(table.getValueAt(selectedRow, 0).toString());
            btSave.setVisible(true);
            edId.setVisible(true);
            jLabel1.setVisible(true);
            edId.setEditable(false);
            jTabbedPane1.setSelectedIndex(0);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um item da tabela!");
        }
    }//GEN-LAST:event_btEditActionPerformed

    private void btSavebtSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSavebtSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSavebtSaveActionPerformed

    private void edSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edSearchActionPerformed

    private void btSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchActionPerformed
        // TODO add your handling code here:
        buildTable(btSearch.getText());
    }//GEN-LAST:event_btSearchActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */    }

    private boolean verifyValuesIfItsNotEmpty() {
        boolean haveEmptyValue = false;

        if (edId.getText().isEmpty()) {
            haveEmptyValue = true;
        }
        if (edIdAccount.getText().isEmpty()) {
            haveEmptyValue = true;
        }
        if (edIdCashier.getText().isEmpty()) {
            haveEmptyValue = true;
        }
        if (edDateReceivement.getText().isEmpty()) {
            haveEmptyValue = true;
        }
        if (edTotalAmountReceivable.getText().isEmpty()) {
            haveEmptyValue = true;
        }
        if (cbPagForm.getSelectedIndex() != -1) {
            haveEmptyValue = true;
            
        }
        return haveEmptyValue;
    }

    private void saveProduct() {
        if (!verifyValuesIfItsNotEmpty()) {
            Receivement rcvmt = new Receivement();
            rcvmt.setId_receivement(Integer.parseInt(edId.getText()));
            rcvmt.setId_acc_receivement(Integer.parseInt(edIdAccount.getText()));
            rcvmt.setId_cashier_receivement(Integer.parseInt(edIdCashier.getText()));
            rcvmt.setDate_receivement(edDateReceivement.getText());
            rcvmt.setTotal_amount_receivable(Float.parseFloat(edTotalAmountReceivable.getText()));

            ReceivementDAO.insert(rcvmt);
            buildTable("");
            jTabbedPane1.setSelectedIndex(1);
            clear();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Algum campo está em branco", null, JOptionPane.WARNING_MESSAGE);
        }

    }

    private void buildTable(String name) {
        ReceivementDAO rDAO = new ReceivementDAO();
        List<Receivement> list = rDAO.getListReceivement(name);
        DefaultTableModel tableModel = (DefaultTableModel) table.getModel();
        tableModel.setRowCount(0);

        for (Receivement rcvmt : list) {
            tableModel.addRow(new Object[]{rcvmt.getId_receivement(), rcvmt.getId_acc_receivement(), rcvmt.getId_cashier_receivement(), rcvmt.getDate_receivement(), rcvmt.getTotal_amount_receivable()});
        }

    }

    private void clear() {
        edDateReceivement.setText(null);
        edId.setText(null);
        edIdAccount.setText(null);
        edIdCashier.setText(null);
        edTotalAmountReceivable.setText(null);
        cbPagForm.setSelectedIndex(-1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btSave;
    private javax.swing.JButton btSearch;
    private javax.swing.JComboBox<String> cbPagForm;
    private javax.swing.JFormattedTextField edDateReceivement;
    private javax.swing.JTextField edId;
    private javax.swing.JTextField edIdAccount;
    private javax.swing.JTextField edIdCashier;
    private javax.swing.JTextField edSearch;
    private javax.swing.JTextField edTotalAmountReceivable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
