/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.EmployeeDAO;
import dao.ProductDAO;
import dao.ServiceDAO;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Employee;
import model.Product;
import model.Service;
import model.ServiceEmployee;
import util.Alert;

/**
 *
 * @author vinij
 */
public class SalesViewSelectService extends javax.swing.JDialog {

    /**
     * Creates new form SalesViewSelectService
     */
    public SalesViewSelectService(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        buildTable("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        edNextStep = new javax.swing.JButton();
        btSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableServices = new javax.swing.JTable();
        edSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selecione um serviço para a venda");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(90, 90, 90));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SELECIONE UM SERVIÇO PARA A VENDA");

        edNextStep.setBackground(new java.awt.Color(87, 126, 244));
        edNextStep.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        edNextStep.setForeground(new java.awt.Color(255, 255, 255));
        edNextStep.setText("PRÓXIMO PASSO");
        edNextStep.setBorderPainted(false);
        edNextStep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edNextStep.setFocusPainted(false);
        edNextStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edNextStepActionPerformed(evt);
            }
        });

        btSearch.setBackground(new java.awt.Color(90, 90, 90));
        btSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_search_white_18dp.png"))); // NOI18N
        btSearch.setBorderPainted(false);
        btSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSearch.setFocusPainted(false);
        btSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });

        tableServices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome Serviço", "Descrição Serviço", "Preço", "Duração em Minutos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableServices);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(390, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(edNextStep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(edSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edNextStep)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchActionPerformed
        // TODO add your handling code here:
        buildTable(edSearch.getText());
    }//GEN-LAST:event_btSearchActionPerformed

    private void edNextStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edNextStepActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableServices.getSelectedRow();
        if (selectedRow > -1) {
            Service s = new Service();

            int id = Integer.parseInt(tableServices.getValueAt(selectedRow, 0).toString());
            String name = tableServices.getValueAt(selectedRow, 1).toString();
            float price = Float.parseFloat(tableServices.getValueAt(selectedRow, 3).toString());
            int duration = Integer.parseInt(tableServices.getValueAt(selectedRow, 4).toString());
            String description = tableServices.getValueAt(selectedRow, 2).toString();

            s.setIdService(id);
            s.setName(name);
            s.setPrice(price);
            s.setDurationService(duration);
            s.setDescription(description);

            List<Employee> employees = EmployeeDAO.getListEmployee("");
            String employeesNames[] = new String[employees.size()];

            for (int i = 0; i < employees.size(); i++) {
                employeesNames[i] = employees.get(i).getPerson().getName() + ","
                        + employees.get(i).getPerson().getCpf();

            }

            JComboBox cbEmployees = new JComboBox(employeesNames);

            int res = JOptionPane.showConfirmDialog(null, cbEmployees, "Selecione o funcionário que realizou o serviço:", JOptionPane.INFORMATION_MESSAGE);

            if (res == 0) {
                if (cbEmployees.getSelectedIndex() > -1) {
                    Employee e = employees.get(cbEmployees.getSelectedIndex());
                    ServiceEmployee se = new ServiceEmployee();
                    se.setEmployee(e);
                    se.setService(s);
                    SalesView.addServicesAndEmployees(se);
                    SalesView.addTotalValue(Double.parseDouble(
                            String.valueOf(se.getService().getPrice())));
                    SalesView sv = new SalesView(null, rootPaneCheckingEnabled);

                    sv.buildTableServicesSale();
                    sv.buildTableProductsSale();
                    sv.setJTabbedPanelIndex(1);

                    this.dispose();
                    sv.setVisible(true);

                    /*P A R E I  AQUI -----------------------------------------------------------------*/
                }
            }

            // Alert.showMessageDialog(e.getPerson().getName());
            /*
            if (Integer.parseInt(qtdResult) <= p.getStock()) {
                ProductSale ps = new ProductSale();
                ps.setProduct(p);
                ps.setQtdProductSale(Integer.parseInt(qtdResult));
                SalesView.addProductsSale(ps);

                /*System.out.println("Nome produto venda: " + sv.getProductSale().getName() + "\n "
                    + "Quantidade produto a ser vendido: " + sv.getQtdProductSale());*/
 /*this.dispose();
                SalesView sv = new SalesView(null, rootPaneCheckingEnabled);
                sv.buildTableProductsSale();
                sv.setVisible(true);
                sv.setLocationRelativeTo(null);
            } else {
                Alert.showWarningMessageDialog("Produto insuficiente no estoque!");
            }

        } else {
            Alert.showWarningMessageDialog("Selecione um produto da tabela para continuar a venda!");
        }
             */
    }//GEN-LAST:event_edNextStepActionPerformed
        else {
            Alert.showWarningMessageDialog("Selecione um serviço da tabela para continuar a venda!");
        }
        //Coloca cb para selecionar funcionário que fez o serviço
    }

    private void buildTable(String name) {
        ServiceDAO servDAO = new ServiceDAO();
        List<Service> list = servDAO.getListService(name);
        DefaultTableModel tableModel = (DefaultTableModel) tableServices.getModel();
        tableModel.setRowCount(0);

        for (Service serv : list) {
            tableModel.addRow(new Object[]{
                serv.getIdService(),
                serv.getName(),
                serv.getDescription(),
                serv.getPrice(),
                serv.getDurationService()});
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesViewSelectService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesViewSelectService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesViewSelectService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesViewSelectService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SalesViewSelectService dialog = new SalesViewSelectService(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSearch;
    private javax.swing.JButton edNextStep;
    private javax.swing.JTextField edSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableServices;
    // End of variables declaration//GEN-END:variables
}
