/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.EmployeeDAO;
import dao.UserDAO;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import model.Employee;
import model.User;
import util.Alert;

/**
 *
 * @author vinij
 */
public class UserView extends javax.swing.JDialog {

    /**
     * Creates new form UserView
     */
    public UserView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
            UIManager.put("TabbedPane.borderHightlightColor", new Color(90, 90, 90));
            UIManager.put("TabbedPane.darkShadow", new Color(90, 90, 90));
            UIManager.put("TabbedPane.light", new Color(90, 90, 90));
            UIManager.put("TabbedPane.selectHighlight", new Color(90, 90, 90));
            UIManager.put("TabbedPane.darkShadow", new Color(90, 90, 90));
            UIManager.put("TabbedPane.focus", new Color(90, 90, 90));

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        initComponents();
        buildTable("");

        chargeCbFunctionary();
        
     

        table.getTableHeader().setOpaque(false);
        table.getTableHeader().setBackground(new Color(61, 59, 59));
        table.getTableHeader().setForeground(Color.WHITE);

    }

    public JPanel getPainel() {
        return this.painelCreateUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelCreateUser = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        edPasswordUser = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        cbEmployee = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        edNameUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btCancel = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        btCreateUser = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        edSearch = new javax.swing.JTextField();
        btnEdit = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        painelCreateUser.setBackground(new java.awt.Color(90, 90, 90));
        painelCreateUser.setForeground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(90, 90, 90));
        jTabbedPane1.setForeground(new java.awt.Color(30, 30, 30));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jTabbedPane1.setOpaque(true);
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(48, 33));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTabbedPane1MousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(90, 90, 90));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        edPasswordUser.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.add(edPasswordUser);
        edPasswordUser.setBounds(130, 260, 321, 26);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CADASTRAR USUÁRIO");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(210, 10, 260, 32);

        cbEmployee.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cbEmployee.setForeground(new java.awt.Color(51, 51, 51));
        cbEmployee.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cbEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEmployeeActionPerformed(evt);
            }
        });
        jPanel1.add(cbEmployee);
        cbEmployee.setBounds(130, 150, 320, 26);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FUNCIONÁRIO");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 130, 129, 20);

        edNameUser.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.add(edNameUser);
        edNameUser.setBounds(130, 210, 321, 26);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SENHA");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 240, 47, 20);

        btCancel.setBackground(new java.awt.Color(200, 76, 88));
        btCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btCancelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btCancelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btCancelMouseReleased(evt);
            }
        });

        jLabel33.setBackground(new java.awt.Color(219, 219, 219));
        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Cancelar");

        javax.swing.GroupLayout btCancelLayout = new javax.swing.GroupLayout(btCancel);
        btCancel.setLayout(btCancelLayout);
        btCancelLayout.setHorizontalGroup(
            btCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btCancelLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel33)
                .addGap(18, 18, 18))
        );
        btCancelLayout.setVerticalGroup(
            btCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btCancelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(btCancel);
        btCancel.setBounds(510, 220, 94, 32);

        btCreateUser.setBackground(new java.awt.Color(99, 154, 103));
        btCreateUser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btCreateUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btCreateUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btCreateUserMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btCreateUserMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btCreateUserMouseReleased(evt);
            }
        });

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Salvar");

        javax.swing.GroupLayout btCreateUserLayout = new javax.swing.GroupLayout(btCreateUser);
        btCreateUser.setLayout(btCreateUserLayout);
        btCreateUserLayout.setHorizontalGroup(
            btCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btCreateUserLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel34)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        btCreateUserLayout.setVerticalGroup(
            btCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btCreateUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(btCreateUser);
        btCreateUser.setBounds(510, 170, 94, 32);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NOME DE USUÁRIO");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(130, 190, 129, 20);

        jTabbedPane1.addTab("CADASTRAR USUÁRIO", jPanel1);

        jPanel2.setBackground(new java.awt.Color(90, 90, 90));
        jPanel2.setPreferredSize(new java.awt.Dimension(48, 33));
        jPanel2.setLayout(null);

        btnSearch.setBackground(new java.awt.Color(90, 90, 90));
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSearchMousePressed(evt);
            }
        });
        btnSearch.setLayout(new java.awt.GridBagLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_search_white_18dp.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setPreferredSize(new java.awt.Dimension(48, 33));
        jLabel4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel4KeyPressed(evt);
            }
        });
        btnSearch.add(jLabel4, new java.awt.GridBagConstraints());

        jPanel2.add(btnSearch);
        btnSearch.setBounds(587, 42, 48, 40);

        table.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME DE USUÁRIO", "NOME DO FUNCIONÁRIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        table.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        table.setFillsViewportHeight(true);
        table.setFocusCycleRoot(true);
        table.setGridColor(new java.awt.Color(204, 204, 204));
        table.setRowHeight(25);
        table.setRowSelectionAllowed(false);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 120, 660, 360);

        edSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edSearchActionPerformed(evt);
            }
        });
        jPanel2.add(edSearch);
        edSearch.setBounds(290, 50, 300, 33);

        btnEdit.setBackground(new java.awt.Color(87, 126, 244));
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEdit.setPreferredSize(new java.awt.Dimension(48, 33));
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEditMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEditMouseReleased(evt);
            }
        });
        btnEdit.setLayout(new java.awt.GridBagLayout());

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_edit_white_18dp.png"))); // NOI18N
        jLabel31.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel31KeyPressed(evt);
            }
        });
        btnEdit.add(jLabel31, new java.awt.GridBagConstraints());

        jPanel2.add(btnEdit);
        btnEdit.setBounds(130, 50, 46, 33);

        btnCreate.setBackground(new java.awt.Color(99, 154, 103));
        btnCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCreate.setPreferredSize(new java.awt.Dimension(48, 33));
        btnCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCreateMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCreateMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCreateMouseReleased(evt);
            }
        });
        btnCreate.setLayout(new java.awt.GridBagLayout());

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_add_white_18dp.png"))); // NOI18N
        jLabel32.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCreate.add(jLabel32, new java.awt.GridBagConstraints());

        jPanel2.add(btnCreate);
        btnCreate.setBounds(60, 50, 46, 33);

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CLIQUE DUAS VEZES SOBRE UM ITEM DA TABELA PARA EXCLUÍ-LO");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 100, 440, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("LISTA DE USUÁRIOS");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(220, 0, 230, 40);

        jTabbedPane1.addTab("LISTAR USUÁRIOS", jPanel2);

        javax.swing.GroupLayout painelCreateUserLayout = new javax.swing.GroupLayout(painelCreateUser);
        painelCreateUser.setLayout(painelCreateUserLayout);
        painelCreateUserLayout.setHorizontalGroup(
            painelCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCreateUserLayout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        painelCreateUserLayout.setVerticalGroup(
            painelCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCreateUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCreateUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMousePressed
        // TODO add your handling code here:       
        buildTable(edSearch.getText());
    }//GEN-LAST:event_btnSearchMousePressed

    private void tableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMousePressed
        int selectedRow = table.getSelectedRow();
        if (evt.getClickCount() == 2 && selectedRow != -1) {
            String idUser = table.getValueAt(selectedRow, 0).toString();
            String userName = table.getValueAt(selectedRow, 1).toString();
            boolean accepted = Alert.showOptionDialog("Deseja deletar o usuário: \n " + idUser + " - " + userName, "Confirmação");
            if (accepted) {
                UserDAO.delete(Integer.parseInt(table.getValueAt(selectedRow, 0).toString()));
                buildTable("");
            }
        }
    }//GEN-LAST:event_tableMousePressed

    private void jTabbedPane1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MousePressed
        // TODO add your handling code here:
        buildTable("");
    }//GEN-LAST:event_jTabbedPane1MousePressed

    private void edSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edSearchActionPerformed

    private void btnEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseEntered
        // TODO add your handling code here:
        btnEdit.setBackground(new Color(87, 126, 244));
    }//GEN-LAST:event_btnEditMouseEntered

    private void btnEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseExited

        btnEdit.setBackground(new Color(87, 126, 244));
    }//GEN-LAST:event_btnEditMouseExited

    private void btnEditMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnEditMousePressed

    private void btnEditMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditMouseReleased

    private void btnCreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateMouseEntered
        // TODO add your handling code here:
        btnCreate.setBackground(new Color(99, 154, 103));
    }//GEN-LAST:event_btnCreateMouseEntered

    private void btnCreateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateMouseExited
        // TODO add your handling code here:
        btnCreate.setBackground(new Color(99, 154, 103));
    }//GEN-LAST:event_btnCreateMouseExited

    private void btnCreateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateMousePressed

    private void btnCreateMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateMouseReleased

    private void btCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCancelMouseEntered
        // TODO add your handling code here:
        btCancel.setBackground(new Color(188, 77, 71));
    }//GEN-LAST:event_btCancelMouseEntered

    private void btCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCancelMouseExited

        btCancel.setBackground(new Color(216, 83, 76));
    }//GEN-LAST:event_btCancelMouseExited

    private void btCancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCancelMousePressed
        // TODO add your handling code here:
        edNameUser.setText("");
        edPasswordUser.setText("");
        cbEmployee.setSelectedIndex(0);
    }//GEN-LAST:event_btCancelMousePressed

    private void btCancelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCancelMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btCancelMouseReleased

    private void btCreateUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCreateUserMouseEntered
        // TODO add your handling code here:
        btCreateUser.setBackground(new Color(80, 156, 81));
    }//GEN-LAST:event_btCreateUserMouseEntered

    private void btCreateUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCreateUserMouseExited
        // TODO add your handling code here:
        btCreateUser.setBackground(new Color(88, 185, 90));
    }//GEN-LAST:event_btCreateUserMouseExited

    private void btCreateUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCreateUserMousePressed
        // TODO add your handling code here:
        if (cbEmployee.getSelectedItem() != null) {
            if (!edNameUser.getText().equals("")) {
                if (!edPasswordUser.getText().equals("")) {
                    User u = new User();
                    u.setName(edNameUser.getText());
                    u.setPassword(edPasswordUser.getText());
                    u.setEmployee((Employee) cbEmployee.getSelectedItem());
                    UserDAO.insert(u);
                } else {
                    Alert.showMessageDialog("Insira uma senha!");
                }
            } else {
                Alert.showMessageDialog("Insira o nome de usuário!");
            }
        } else {
            Alert.showMessageDialog("Selecione um funcionário!");
        }

    }//GEN-LAST:event_btCreateUserMousePressed

    private void btCreateUserMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCreateUserMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btCreateUserMouseReleased

    private void cbEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEmployeeActionPerformed

    private void jLabel4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel4KeyPressed
        // TODO add your handling code here:
        buildTable(edSearch.getText());
    }//GEN-LAST:event_jLabel4KeyPressed

    private void jLabel31KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel31KeyPressed
        // TODO add your handling code here:
        int selectedRow = table.getSelectedRow();

       

    }//GEN-LAST:event_jLabel31KeyPressed

    private void buildTable(String s) {
        UserDAO udao = new UserDAO();
        List<User> list = udao.getListUser(s);
        DefaultTableModel tableModel = (DefaultTableModel) table.getModel();
        tableModel.setRowCount(0);

        for (User u : list) {
            tableModel.addRow(new Object[]{
                u.getId(),
                u.getName(),
                u.getEmployee().getPerson().getName()
            });
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserView dialog = new UserView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void chargeCbFunctionary() {
        List<Employee> employees = EmployeeDAO.getListEmployee("");
        cbEmployee.removeAll();

        for (Employee e : employees) {
            cbEmployee.addItem(e);
        }
        cbEmployee.setSelectedItem(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btCancel;
    private javax.swing.JPanel btCreateUser;
    private javax.swing.JPanel btnCreate;
    private javax.swing.JPanel btnEdit;
    private javax.swing.JPanel btnSearch;
    private javax.swing.JComboBox<Object> cbEmployee;
    private javax.swing.JTextField edNameUser;
    private javax.swing.JPasswordField edPasswordUser;
    private javax.swing.JTextField edSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel painelCreateUser;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
